title = "Jennifer Appleby | Portfolio"
baseURL = "https://jenapp.github.io/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
favicon = "/favicon.ico"
firstName = "Jennifer"
lastName = "Appleby"
address = "Melbourne, Australia"
email = "jennifer.appleby@gmail.com"
phone = "(+61) 0413 693 429"
profileImage = "img/J.jpg"
showQr = false
showContact = true
sections = ["skills","publications","creations","contributions","experience","education","blog"]

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

[[params.handles]]
link = "https://www.linkedin.com/in/jennifer-appleby"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jenapp"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"